package com.myFileSys.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setAge(java.lang.Integer age) {
		set("age", age);
		return (M)this;
	}
	
	public java.lang.Integer getAge() {
		return getInt("age");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public M setLogin(java.lang.Integer login) {
		set("login", login);
		return (M)this;
	}
	
	public java.lang.Integer getLogin() {
		return getInt("login");
	}

	public M setUserType(java.lang.Integer userType) {
		set("userType", userType);
		return (M)this;
	}
	
	public java.lang.Integer getUserType() {
		return getInt("userType");
	}

	public M setHeadImg(java.lang.String headImg) {
		set("headImg", headImg);
		return (M)this;
	}
	
	public java.lang.String getHeadImg() {
		return getStr("headImg");
	}

}
