package com.myFileSys.common.model;

import com.myFileSys.common.model.base.BaseDocument;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Document extends BaseDocument<Document> {
	
}
