package com.myFileSys.common.model;

import com.myFileSys.common.model.base.BaseGroupRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class GroupRule extends BaseGroupRule<GroupRule> {
	
}
