package com.myFileSys.common.model;

import com.myFileSys.common.model.base.BaseMemuRule;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MemuRule extends BaseMemuRule<MemuRule> {
	
}
