package com.myFileSys.common.model;

import com.jfinal.plugin.activerecord.Db;
import com.myFileSys.common.model.base.BaseMovie;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Movie extends BaseMovie<Movie> {
	
	
}
