package com.myFileSys.common.model;

import com.myFileSys.common.model.base.BasePicture;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Picture extends BasePicture<Picture> {
	
}
